# This is a basic workflow to help you get started with Actions

name: GitHub Pages Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node and Build
      - uses: actions/setup-node@v2.1.2
      - name: Setup Node.js environment
        run: |
          yarn install
          yarn build

      # Upload artifacts
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Download artifacts
      - name: Download and deploy
        uses: actions/download-artifact@v2
        with:
          name: dist

      # Commit and deploy
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git init
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          git add -A
          git commit -m 'deploy'
          git push -f github HEAD:gh-pages
